GROQ_API_KEY: 'gsk_TGuOxxkwfbEcqcaMKHFeWGdyb3FY1qsZNVnzYQqPC4l9cDYWtk2oPgE'
GEMINI_API_KEY: 'AIzaSyBvMmSqEX6EWbHD101touDeqK8rm3TIs_Q'
GROQ_API: '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'

